ngzblog/blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    # url(r'^backend/$', views.backend),
    # url(r'^add_article/$', views.add_article),
    # url(r'^upload/$', views.upload),
    # url(r'^(\w+)/$', views.home),
    url(r'^(\w[a-zA-Z]\w{5,17}@163.com)/(category|tag|archive)/(.*)/$', views.home),  # home(request, username, category, xx)
    url(r'^(\w[a-zA-Z]\w{5,17}@163.com)/p/(\d+)', views.article),
]

ngzblog/ngzblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog import views
from django.views.static import serve
from django.conf import settings
from blog import urls as blog_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.Login.as_view()),
    url(r'^logout/', views.logout),
    url(r'^v-code/$', views.v_code),
    url(r'^reg/$', views.RegView.as_view()),
    url(r'^$', views.Index.as_view()),
    url(r'^index/$', views.Index.as_view()),
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
    url(r'^blog/', include(blog_urls)),
    url(r'^dianzan/$', views.dianzan),
    url(r'^comment/$', views.comment),
    url(r'^comment/(\d+)$', views.Comment.as_view()),
]

ngzblog/blog/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username = forms.CharField(
        label='用户名',
        min_length=4,
        error_messages={
            "required": "用户名不能为空",
            "min_length": "用户名不能少于4位"
        },
        widget=forms.widgets.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "用户名",
                "aria-describedby": "basic-addon1",
            }
        )
    )
    password = forms.CharField(
        label="密码",
        min_length=6,
        error_messages={
            "required": "密码不能为空",
            "min_length": "密码不能少于6位"
        },
        widget=forms.widgets.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "密码",
            }
        )
    )


class RegisterForm(forms.Form):
    username = forms.CharField(
        label='用户名',
        min_length=4,
        error_messages={
            "required": "用户名不能为空",
            "min_length": "用户名不能少于4位"
        },
        widget=forms.widgets.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "用户名",
            }
        )
    )
    password = forms.CharField(
        label="密码",
        min_length=6,
        error_messages={
            "required": "密码不能为空",
            "min_length": "密码不能少于6位"
        },
        widget=forms.widgets.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "密码",
            }
        )
    )
    re_password = forms.CharField(
        label="确认密码",
        min_length=6,
        error_messages={
            "required": "密码不能为空",
            "min_length": "密码不能少于6位"
        },
        widget=forms.widgets.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "确认密码",
            }
        )
    )

    # phone = forms.CharField(
    #     label='手机号',
    #     error_messages={
    #         "required": "手机号不能为空",
    #     },
    #     validators=[RegexValidator(r'1[3-9]\d{9}', "手机号码格式不正确")],
    #     widget=forms.widgets.TextInput(
    #         attrs={"class": "form-control"}
    #     )
    # )

    # 全局钩子
    def clean(self):
        pwd = self.cleaned_data.get("password")
        re_pwd = self.cleaned_data.get("re_password")
        if re_pwd and re_pwd == pwd:
            return self.cleaned_data
        else:
            self.add_error('re_password', "两次密码不一致")
            raise ValidationError("两次密码不一致")

ngzblog/templates/article.html
{% extends 'base.html' %}
{% block page-main %}
    <div class="col-md-12">
        <div class="list-group" style="background-color: rgba(255,255,255,1);border: 1px solid rgba(247,238,214,1); width: 79%; margin-top: 15px; padding-left: 10px;">

                    <h1>{{ article.title }}</h1>
            <hr class="hr_1">
                <p>{{ article.articledetail.content|safe }}</p>
        </div>
<div class="col-md-10">
<div class="clearfix">
        <div id="div_digg">
            <!-- 点赞 -->
            <div class="diggit digg" >
                <span class="diggnum" id="digg_count">{{ article.up_count }}</span>
            </div>
            <!-- 反对 -->
            <div class="buryit digg">
                <span class="burynum" id="bury_count">{{ article.down_count }}</span>
            </div>
            <div class="clear"></div>
            <!-- 提示信息 -->
            <div class="diggword" id="digg_tips"></div>
        </div>
    </div>
</div>
    </div>

{% csrf_token %}
    <hr>
        <!-- 点赞 开始-->


    <!-- 点赞 结束-->

    <!-- 评论展示区 开始 -->
    <h4>评论：</h4>
    <div>
        <div class="list-group comment-list" style="width: 79%;">
            {% for comment in comment_list %}
                <div class="list-group-item" href="#" my-id="{{ comment.id }}">
                    <h4 class="list-group-item-heading comment-header">
                        <span>{{ forloop.counter }}楼</span>
                        <span>{{ comment.create_time|date:'Y-m-d H:i' }}</span>
                        <span>{{ comment.user.username }}</span>
                        <span class="pull-right replay">回复</span>
                    </h4>
                    {% if comment.parent_comment %}
                        <span style="display: block">@{{ comment.parent_comment.user.username }}</span>
                        <p class="list-group-item-text well">
                            {{ comment.parent_comment.content }}
                        </p>
                    {% endif %}
                    <p class="list-group-item-text comment-content">
                        {{ comment.content }}
                    </p>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- 评论展示区 结束 -->
    <hr>

    <!-- 发表评论 开始 -->
    <h4>发表评论</h4>
    <div>
        <span>用户名：</span>
        <input type="text" value="{{ request.user.username }}" disabled>
    </div>
    <div>
        <p>发表评论：</p>
        <textarea name="" id="new-comment" cols="60" rows="10"></textarea>
    </div>
    <div>
        <button id="submit-comment" class="btn btn-success">提交</button>
    </div>
    <!-- 发表评论 结束 -->


    <div style="height: 300px"></div>

{% endblock %}

{% block page-js %}
    <script>
        $('.digg').click(function () {
            if (!'{{ request.user.username }}'){
                location.href='/login/?next={{ request.get_full_path }}'
            }

            var userId = '{{ request.user.id }}';
            var articleId = '{{ article.id }}';
            var isUP = $(this).hasClass('diggit');
            //console.log(userId);
            $.ajax({
                url:'/dianzan/',
                type:'post',
                data:{
                    csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val(),
                    userId:userId,
                    articleId:articleId,
                    isUP:isUP
                },
                success:function (res) {
                    //console.log(res);
                    if (res.code !== 0){
                        $('#digg_tips').text(res.msg)
                    }else {
                        if (isUP){
                            var $UpSpan = $('$digg_count');
                            $UpSpan.text(+$UpSpan.text()+1);
                        } else {
                            var $downSpan = $('$bury_count');
                            $downSpan.text(+$downSpan.text()+1);
                        }
                        $('#digg_tips').text(res.msg)
                    }
                }
            })
        });

        $('#submit-comment').click(function () {
            var userId = '{{ request.user.id }}';
            var content = $('#new-comment').val();
            var articleId = '{{ article.id }}';
            var parentId = $(this).data('pid') || '';
            if (parentId){
                content = content.slice(content.indexOf('\n')+1,);
            }
            $.ajax({
                url:'/comment/',
                type:'post',
                data:{
                    parent_id:parentId,
                    user_id:userId,
                    content:content,
                    article_id:articleId,
                    csrfmiddlewaretoken:$('[name="csrfmiddlewaretoken"]').val(),
                },
                success:function (res) {
                    //console.log(res);
                    if (res.code === 0){
                        var data = res.data;
                        var num = $('.comment-list>div').length + 1;
                        var commentHtml = `
                        <div href="#" class="list-group-item">
                            <h4 class="list-group-item-heading comment-header">
                                <span>${ num }楼</span>
                                <span>${ data.create_time }</span>
                                <span>${ data.username }</span>
                                <span class="huifu pull-right replay">回复</span>
                            </h4>
                            <p class="list-group-item-text comment-content">
                                ${ data.content }
                            </p>
                        </div>
                        `;
                        $('.comment-list').append(commentHtml);
                        $('#new-comment').val('');
                        $('#submit-comment').removeData('pid');
                    }
                }
            })
        });

        $('.comment-list').on('click', '.replay', function () {
            var replayName = $(this).prev().text();
            $('#new-comment').focus().val('@'+replayName+'\n');
            var pID = $(this).parent().parent().attr('my-id');
            $('#submit-comment').data('pid',pID);
        })
    </script>
{% endblock %}

ngzblog/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>雪落的瞬间</title>
    <link href="https://img2018.cnblogs.com/blog/1385912/201811/1385912-20181126185759473-1237923276.png" rel="SHORTCUT ICON">
    <link href="/static/bootstrap-3.3.7/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/base.css">
</head>
<body>
<div class="row">
    <nav class="navbar navbar-inverse" style="width: 100%;">
        <div class="col-md-8 col-md-offset-2 .col-xs-8 .col-sm-8">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand a-blog" href="/index/" style="color: rgb(255,255,255);">雪落的瞬间博客</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse title" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav title-center">
                        <li><a href="/index/">首页</a></li>
                        <li class="python"><a href="/blog/nieguangzong124@163.com/category/python/">Python</a></li>
                        <li class="mydow"><a href="/blog/nieguangzong124@163.com/category/PHP/" class="mydow">PHP</a></li>
                        <li class="mysql"><a href="/blog/nieguangzong124@163.com/category/mysql/" class="mysql">MySQL</a></li>
                        <li class="web"><a href="/blog/nieguangzong124@163.com/category/web/" class="web">前端</a></li>
                        <li class="video"><a href="/blog/nieguangzong124@163.com/category/video/" class="video">影视制作</a></li>
                        <li class="pm"><a href="/blog/nieguangzong124@163.com/category/pm/" class="pm">产品经理</a></li>
                        <li class="mydow"><a href="/blog/nieguangzong124@163.com/category/mydow/" class="mydow">其它</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="">{{ request.user.username }}</a>
                        </li>
                        <li>
                            <img src="/media/{{ request.user.avatar }}" alt=""
                                 style="height: 50px;width: 50px;border-radius: 50%; margin-top: 20px; display:none;">
                        </li>
                        <li class="dropdown">
                            <a href="#" class="glyphicon glyphicon-user" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false"></a>
                            <ul class="dropdown-menu">
                                <li><a href="/login/">登陆</a></li>
                                <li><a href="/logout/">注销</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</div>

<div class="container-fluid container-1">
    <div class="col-md-12 .col-xs-12 .col-sm-12">
        <nav class="navbar na-2">

            <div class="collapse navbar-collapse title2" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav top-content">
                    <li><a href="#" style="color: rgb(255,255,255);">python基础</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">Python函数</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">Python模块与包</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">面向对象</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">网络/并发编程</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">Django框架</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">Flask框架</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">Tornado框架</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">爬虫</a></li>
                </ul>
            </div>


        </nav>
    </div>
</div>

<div class="container container-2">
    <div class="col-md-12 .col-xs-12 .col-sm-12">
        <nav class="navbar na-2">

            <div class="collapse navbar-collapse title3" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav top-content">
                    <li><a href="#" style="color: rgb(255,255,255);">MySQL安装与基本管理</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">语句</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">库</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">表</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">数据类型</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">外键</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">数据增删改</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">表查询</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">其它</a></li>
                </ul>
            </div>


        </nav>
    </div>
</div>

<div class="container container-3">
    <div class="col-md-12 .col-xs-12 .col-sm-12">
        <nav class="navbar na-2">

            <div class="collapse navbar-collapse title4" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav top-content">
                    <li><a href="#" style="color: rgb(255,255,255);">HTML</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">CSS</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">JavaScript基础</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">jQuery</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">响应式之Bootstrap</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">ES6</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">vue</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">其它</a></li>
                </ul>
            </div>


        </nav>
    </div>
</div>

<div class="container container-4">
    <div class="col-md-12 .col-xs-12 .col-sm-12">
        <nav class="navbar na-2">

            <div class="collapse navbar-collapse title5" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav top-content">
                    <li><a href="#" style="color: rgb(255,255,255);">影视概念全流程</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">PS与Matepatting</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">Maya</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">Nuke</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">SFX silhouette</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">Mocha</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">其它</a></li>
                </ul>
            </div>


        </nav>
    </div>
</div>

<div class="container container-5">
    <div class="col-md-12 .col-xs-12 .col-sm-12">
        <nav class="navbar na-2">

            <div class="collapse navbar-collapse title6" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav top-content">
                    <li><a href="#" style="color: rgb(255,255,255);">产品经理入门</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">进阶</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">永无止尽</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">实战项目</a></li>
                    <li><a href="#" style="color: rgb(255,255,255);">其它</a></li>
                </ul>
            </div>


        </nav>
    </div>
</div>

<div class="col-md-10 col-md-offset-2">
    {% block page-main %}

    {% endblock page-main %}
</div>

<div class="container" style="margin-bottom: 20px;">
    <div class="row">
        <div class="col-md-4 col-md-offset-10">
            <button id='retopbtn' onclick='returnTop()'
                    class="btn btn-success btn-lg text-center glyphicon glyphicon-open"></button>
        </div>
    </div>
</div>


<div class="row bottom_down">
    <div class="col-md-4 col-lg-offset-5" style="margin-top: 15px;">
        <a class="navbar-brand a-blog" href="#" style="color: rgb(117,117,117); font-size: 20px; cursor:default;">本站备案号：鲁ICP备18050375号</a>
    </div>
</div>


<script src="/static/js/jquery.js"></script>
<script src="/static/bootstrap-3.3.7/js/bootstrap.js"></script>
<script type="text/javascript">

    // $('.python').mouseover(function(event) {
    // 	$('.container-1').stop().slideDown(250);
    // 	$('.container-1').mouseenter(function(event){
    // 		$(this).stop().show();
    // 	});
    // 	$('.container-1').mouseleave(function(event) {
    // 		$(this).stop().slideUp(250);
    // 	});
    // });

    $('.mysql').mouseover(function (event) {
        // $('.container-2').stop().slideDown(250);
        $('.container-2').mouseenter(function (event) {
            $(this).stop().show();
        });
        $('.container-2').mouseleave(function (event) {
            $(this).stop().slideUp(250);
        });
    });
    $('.web').mouseover(function (event) {
        // $('.container-3').stop().slideDown(250);
        $('.container-3').mouseenter(function (event) {
            $(this).stop().show();
        });
        $('.container-3').mouseleave(function (event) {
            $(this).stop().slideUp(250);
        });
    });
    $('.video').mouseover(function (event) {
        // $('.container-4').stop().slideDown(250);
        $('.container-4').mouseenter(function (event) {
            $(this).stop().show();
        });
        $('.container-4').mouseleave(function (event) {
            $(this).stop().slideUp(250);
        });
    });
    $('.pm').mouseover(function (event) {
        // $('.container-5').stop().slideDown(250);
        $('.container-5').mouseenter(function (event) {
            $(this).stop().show();
        });
        $('.container-5').mouseleave(function (event) {
            $(this).stop().slideUp(250);
        });
    });

    function showReposBtn() {
        var clientHeight = $(window).height();
        var scrollTop = $(document).scrollTop();
        var maxScroll = $(document).height() - clientHeight;
        //滚动距离超过可视一屏的距离时显示返回顶部按钮
        if (scrollTop > clientHeight) {
            $('#retopbtn').show();
        } else {
            $('#retopbtn').hide();
        }
    }

    window.onload = function () {
        //获取文档对象
        $body = (window.opera) ? (document.compatMode == "CSS1Compat" ? $("html") : $("body")) : $("html,body");
        //显示按钮
        showReposBtn();
    }

    window.onscroll = function () {
        //滚动时调整按钮显隐
        showReposBtn();
    }

    //返回顶部
    function returnTop() {
        $body.animate({scrollTop: 0}, 400);
    }


</script>
{% block page-js %}

{% endblock %}

</body>
</html>

ngzblog/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>login</title>
	<link href="/static/bootstrap-3.3.7/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/login.css">
</head>
<body>
<div class="container">
	<div class="row row_login">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-info">
		      <div class="panel-heading">
		        <h3 class="panel-title text-center">登录博客</h3>
		      </div>
		      <div class="panel-body">
		      	<form class="login-form">
                    {% csrf_token %}
			        <div class="input-group">
	                    <span class="input-group-addon" id="basic-addon1"><label class="glyphicon glyphicon-user" style="display: inline-block;" for="{{ form_obj.username.id_for_label }}"></label></span>
	                    {{ form_obj.username }}
	                </div>
	                <div class="input-group">
	                    <span class="input-group-addon" id="basic-addon1"><label class="glyphicon glyphicon-lock" for="{{ form_obj.password.id_for_label }}"></label></span>
	                    {{ form_obj.password }}
	                </div>
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><label class="glyphicon glyphicon-barcode" for="v-code" style="display: block;"></label></span>
                        <input type="text" id="v-code" class="form-control basic-addon1" placeholder="验证码" style="width: 200px;display: inline-block">
                        <img src="/v-code/" id="i1" style="float: right">
                    </div>

                    <div class="row text-center">
                        <p id="error-p" class="err-text"></p>
                    </div>

                    <div class="text-center">

                        <button id="login-btn" type="button" class="btn btn-primary text-center">登录</button>
                    </div>

                    <div class="pull-right">
                        <a href="/reg/">还没有账号，去注册</a>
                    </div>
                    <br>
                    <div class="pull-right">
                        <a href="/index/">注册什么的都去见鬼吧，我要学知识！</a>
                    </div>



                </form>
                <hr>
                <p>其它账号授权登录：</p>
		      </div>
		    </div>
		</div>
	</div>
</div>

</body>

<script src="/static/js/jquery.js"></script>
<script src="/static/bootstrap-3.3.7/js/bootstrap.js"></script>
<script type="text/javascript">
    $("#login-btn").click(function () {
        // 取用户填写的数据
        let username = $("#id_username").val();
        let pwd = $("#id_password").val();
        let csrfToken = $("[name='csrfmiddlewaretoken']").val();
        let vCode = $("#v-code").val();
        // 发送ajax请求
        $.ajax({
            url: '/login/',
            type: 'post',
            data: {
                username: username,
                password: pwd,
                csrfmiddlewaretoken: csrfToken,
                v_code: vCode
            },
            success:function (res) {
                console.log(res);
                if (res.code !== 0){
                    // 有错误
                    $("#error-p").text(res.msg);
                }else {
                    location.href = '/index/'
                }
            }
        })
    });
    
    $("input").focus(function () {
        $("#error-p").text('');
    });
    // 点击刷新验证码
    $("#i1").click(function () {
        // this.src += "?";
        // 使用正则判断一下：如果原来的url有?就去掉，没有就加上
        var url = this.src;
        if (/\?$/.test(url)){
            // 去掉最后的?
            this.src = url.slice(0,-1);
        }else {
            this.src = url + "?";
        }
        console.log(this.src);
    })
</script>
</html>

ngzblog/templates/register.html
<!DOCTYPE html>
<html>
<head>
	<title>register</title>
    <link href="/static/bootstrap-3.3.7/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/register.css">
</head>
<body>
<div class="container">
	<div class="row row_login">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-info">
		      <div class="panel-heading">
		        <h3 class="panel-title text-center">注册博客 ID</h3>
		      </div>
		      <div class="panel-body">
				            <form class="login-form">
                                {% csrf_token %}
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1"><label class="glyphicon glyphicon-user" for="{{ form_obj.username.id_for_label }}"></label></span>
                    {{ form_obj.username }}
                    <span class="help-block"></span>
                </div>

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1"><label class="glyphicon glyphicon-lock" for="{{ form_obj.password.id_for_label }}"></label></span>
                    {{ form_obj.password }}
                    <span class="help-block"></span>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1"><label class="glyphicon glyphicon-lock" for="{{ form_obj.re_password.id_for_label }}"></label></span>
                    {{ form_obj.re_password }}
                    <span class="help-block"></span>
                </div>
                <div class="input-group">
                    <label for="avatar">头像<img id="avatar-img" src="/static/default.png" alt="" style="height: 80px;width: 80px;margin-left: 15px"></label>
                    <input type="file" accept="image/*" id="avatar" style="display: none;">
                </div>
                                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><label class="glyphicon glyphicon-barcode" for="v-code" style="display: block;"></label></span>
                        <input type="text" id="v-code" class="form-control basic-addon1" placeholder="验证码" style="width: 200px;display: inline-block">
                        <img src="/v-code/" id="i1" style="float: right">
                    </div>

                    <div class="row text-center">
                        <p id="error-p" class="err-text"></p>
                    </div>
                <div class="text-center">
                    <button id="reg-btn" type="button" class="btn btn-success">注册</button>
                </div>

                <div class="pull-right">
                    <a href="/login/">已有账号，去登陆</a>
                </div>
                <br>
                <div class="pull-right">
                    <a href="/index/">注册什么的都去见鬼吧，我要学知识！</a>
                </div>

            </form>
		      </div>
		    </div>
		</div>
	</div>
</div>
</body>
<script src="/static/js/jquery.js"></script>
<script src="/static/bootstrap-3.3.7/js/bootstrap.js"></script>
<script>
    $("#reg-btn").click(function () {
        // 1. 取到用户填写的数据
        var fd = new FormData();
        fd.append("username", $("#id_username").val());
        fd.append("password", $("#id_password").val());
        fd.append("re_password", $("#id_re_password").val());
        fd.append("email", $("#id_email").val());
        fd.append("v_code", $("#v-code").val());
        fd.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());
        fd.append('avatar', $("#avatar")[0].files[0]);
        // 2. 往后端发post请求
        $.ajax({
            url: '/reg/',
            type: 'post',
            data: fd,
            processData: false,
            contentType: false,
            success:function (res) {
                console.log(res);
                if (res.code === 2){
                    // 验证码有错误
                    $("#error-p").text(res.msg);
                }else if (res.code === 0){
                    // 注册成功
                    location.href = res.msg;
                }else if (res.code === 1){
                    console.log(res.msg);
                    // 遍历取出所有的错误提示信息，在页面上展示出来
                    $.each(res.msg, function (k,v) {
                        console.log($("#id_"+k).next().text(v[0]));
                        $("#id_"+k).next().text(v[0]).parent().addClass('has-error');
                    })
                }
            }
        })
    });

    // 每一个input标签获取焦点的时候，把自己下面的span标签内容清空，把父标签的has-error样式移除
    $("input.form-control").focus(function () {
        $(this).val('').next("span").text('').parent().removeClass('has-error');
    });

    $("#v-code").focus(function () {
        $(this).val('').next().next().text('');
    });
    // 前端页面实现头像预览
    // 当用户选中文件之后，也就是头像的input标签有值时触发
    $("#avatar").change(function () {
        // 找到用户选中的那个文件
        var file = this.files[0];
        // 生成一个读文件的对象
        var fr = new FileReader();
        // 从文件中读取头像文件数据
        fr.readAsDataURL(file);
        // 等到读完之后
        fr.onload = function () {
            // 将头像img标签的src属性更换成我选中的那个文件
            $("#avatar-img").attr("src", fr.result)
        }
    })

    // 点击刷新验证码
    $("#i1").click(function () {
        // this.src += "?";
        // 使用正则判断一下：如果原来的url有?就去掉，没有就加上
        var url = this.src;
        if (/\?$/.test(url)){
            // 去掉最后的?
            this.src = url.slice(0,-1);
        }else {
            this.src = url + "?";
        }
        //console.log(this.src);
    })

</script>
</html>